project_id = "ehiemefjuylqfkrkfqgs"

[functions.search-predictive]
verify_jwt = false

[functions.redirect-proxy]
verify_jwt = false

[functions.shopify-webhook]
verify_jwt = false

[functions.sitemap]
verify_jwt = false

[functions.sync-brands]
verify_jwt = false

[functions.generate-brand-seo]
verify_jwt = false