DO $$
DECLARE
  t RECORD;
BEGIN
  FOR t IN (
    SELECT * FROM (VALUES
      ('topbar.free_shipping', 'Free shipping from €50'),
      ('topbar.products_count', 'Over 30,000 products'),
      ('topbar.money_back', '30-day money-back guarantee'),
      ('topbar.phone_advisory', 'Expert advice: +49 4172 6403'),
      ('nav.home', 'Home'),
      ('nav.brands', 'Our Brands'),
      ('nav.news', 'News'),
      ('header.search_open', 'Open search'),
      ('header.account', 'My Account'),
      ('header.login', 'Sign in'),
      ('header.logout', 'Sign out'),
      ('header.logged_out', 'Signed out successfully'),
      ('hero.badge', 'AI-powered search & advice'),
      ('hero.title', 'Find the perfect equipment'),
      ('hero.title_highlight', 'for horse & rider'),
      ('hero.subtitle', 'Search for products, brands and categories — or ask a question and get personalised advice from our AI.'),
      ('hero.search_placeholder', 'Search products or ask a question …'),
      ('hero.popular', 'Popular:'),
      ('hero.chip.winterdecke', 'Winter blanket'),
      ('hero.chip.airbagweste', 'Airbag vest'),
      ('hero.chip.schabracke', 'Saddle pad'),
      ('hero.chip.reithelm', 'Riding helmet'),
      ('hero.chip.gamaschen', 'Boots'),
      ('hero.chip.turnierbekleidung', 'Show clothing'),
      ('hero_section.title', 'Your expert partner for equestrian sports'),
      ('hero_section.subtitle', 'Over 30,000 products for horse and rider. Expert advice on site in Luhmühlen or online.'),
      ('hero_section.cta_shop', 'Shop Now'),
      ('hero_section.cta_phone', 'Advice: 04172-6403'),
      ('services.store.title', 'Equestrian store'),
      ('services.store.desc', 'Over 10,000 items on site. Expert advice in Luhmühlen.'),
      ('services.online.title', 'Online shop'),
      ('services.online.desc', 'Over 30,000 items available online. Fast shipping.'),
      ('services.saddle.title', 'Saddle service'),
      ('services.saddle.desc', 'Mobile saddle service within 50 km. Consultation & fitting.'),
      ('services.embroidery.title', 'Embroidery'),
      ('services.embroidery.desc', 'Custom embroidery for saddle pads, blankets, jackets and more.'),
      ('categories.title', 'What we do best'),
      ('categories.eventing.title', 'Eventing'),
      ('categories.eventing.desc', 'Everything for the eventing rider and the eventing horse.'),
      ('categories.saddles.title', 'Saddles'),
      ('categories.saddles.desc', 'Prestige, Passier, Kentaur and Euroriding – configure online.'),
      ('categories.bits.title', 'Bits'),
      ('categories.bits.desc', 'Germany''s largest bit selection with bit finder.'),
      ('categories.airbag.title', 'Airbag vests'),
      ('categories.airbag.desc', 'Helite & Freejump – expert advice included.'),
      ('products.title', 'Our Products'),
      ('products.loading_error', 'Products could not be loaded.'),
      ('products.empty', 'No products yet'),
      ('products.empty_hint', 'Create your first product by telling us what you would like to sell.'),
      ('products.added_to_cart', 'Added to cart'),
      ('cart.title', 'Shopping Cart'),
      ('cart.empty', 'Your cart is empty'),
      ('cart.items_one', '1 item in cart'),
      ('cart.items_other', '{count} items in cart'),
      ('cart.total', 'Total'),
      ('cart.checkout', 'Checkout'),
      ('product.back', 'Back to shop'),
      ('product.not_found', 'Product not found'),
      ('product.add_to_cart', 'Add to cart'),
      ('product.unavailable', 'Unavailable'),
      ('product.configure_first', 'Please configure first'),
      ('product.description', 'Description'),
      ('product.configure_change', 'Change configuration'),
      ('product.configure_now', 'Configure now'),
      ('product.config_complete', 'Configuration complete'),
      ('product.incl_config', '(incl. configuration)'),
      ('product.advice_title', 'Need advice? Questions about this product?'),
      ('product.advice_subtitle', 'Contact us:'),
      ('product.phone', 'Phone'),
      ('product.contact_form', 'Contact form'),
      ('product.online_advice', 'Online advice'),
      ('cookie.title', '🍪 We use cookies'),
      ('cookie.text', 'We use cookies to provide you with the best possible experience on our website. For more information, please see our'),
      ('cookie.privacy_link', 'Privacy Policy'),
      ('cookie.essential_only', 'Essential only'),
      ('cookie.accept_all', 'Accept all'),
      ('footer.service_hotline', 'Service Hotline'),
      ('footer.phone_support', 'Phone support and advice:'),
      ('footer.hours_weekday', 'Mon–Fri, 10:00 – 18:30'),
      ('footer.hours_saturday', 'Sat, 09:00 – 14:00'),
      ('footer.store_title', 'Store:'),
      ('footer.information', 'Information'),
      ('footer.legal', 'Legal Information'),
      ('footer.about', 'Your expert partner for equestrian sports for many years in Luhmühlen.'),
      ('footer.payment_methods', 'Payment Methods'),
      ('footer.payment_loading', 'Loading payment methods…'),
      ('footer.shipping', 'Shipping Partners'),
      ('footer.buyer_protection', 'Buyer Protection'),
      ('footer.copyright', '© {year} Horse & Rider Luhmühlen. All rights reserved.'),
      ('footer.newsletter_label', 'Subscribe to newsletter:'),
      ('footer.newsletter_placeholder', 'Your email address'),
      ('footer.newsletter_success', '✓ Thank you! You will receive a confirmation email shortly.'),
      ('footer.newsletter_error', 'Subscription failed. Please try again.'),
      ('footer.newsletter_title', 'Newsletter Signup'),
      ('footer.newsletter_consent_text', 'By subscribing, you agree that we may use your email to send info about offers and promotions from Horse & Rider.'),
      ('footer.newsletter_consent_label', 'I agree to the processing of my email according to the privacy policy. I can revoke my consent at any time.'),
      ('footer.cancel', 'Cancel'),
      ('footer.subscribe', 'Subscribe'),
      ('footer.news', 'News & Updates'),
      ('footer.brands', 'Our Brands'),
      ('footer.account', 'My Account'),
      ('footer.shipping_payment', 'Shipping & Payment'),
      ('footer.faq', 'FAQ'),
      ('footer.contact', 'Contact'),
      ('footer.privacy', 'Privacy Policy'),
      ('footer.terms', 'Terms & Conditions'),
      ('footer.imprint', 'Legal Notice'),
      ('footer.withdrawal', 'Right of Withdrawal'),
      ('search.title', 'AI-powered search & advice'),
      ('search.close', 'Close search'),
      ('search.subtitle', 'Search for products, brands and categories or ask questions about equipment for horse and rider.'),
      ('search.placeholder', 'Search products or ask a question …'),
      ('search.clear', 'Clear search'),
      ('search.back', 'Back'),
      ('search.results_for', 'Search results for "{query}"'),
      ('search.search', 'Search'),
      ('search.result_one', '1 result'),
      ('search.result_other', '{count} results'),
      ('search.loading_error', 'Search results could not be loaded.'),
      ('search.no_results', 'No results for "{query}"'),
      ('search.popular_searches', 'Popular Searches'),
      ('search.popular_categories', 'Popular Categories'),
      ('search.trending_products', 'Trending Products'),
      ('search.products', 'Products'),
      ('search.hits', '{count} hits'),
      ('search.no_products', 'No products found for "{query}"'),
      ('search.try_different', 'Try a different search term or ask a question.'),
      ('search.searching', 'Searching…'),
      ('search.ai_advice', 'AI Advice'),
      ('contact.title', 'Product Enquiry'),
      ('contact.subject_prefix', 'Question about product'),
      ('contact.subject', 'Subject'),
      ('contact.email', 'Your email address *'),
      ('contact.email_placeholder', 'your@email.com'),
      ('contact.phone', 'Your phone number'),
      ('contact.message', 'Your message *'),
      ('contact.message_placeholder', 'Your question about the product...'),
      ('contact.send', 'Send enquiry'),
      ('contact.fill_required', 'Please fill in email and message.'),
      ('contact.email_opened', 'Email client is opening'),
      ('notfound.title', '404'),
      ('notfound.message', 'Page not found'),
      ('notfound.back', 'Back to home'),
      ('auth.login', 'Sign in'),
      ('auth.signup', 'Sign up'),
      ('auth.email', 'Email'),
      ('auth.password', 'Password'),
      ('auth.first_name', 'First name'),
      ('auth.last_name', 'Last name'),
      ('auth.forgot_password', 'Forgot password?'),
      ('auth.reset_password', 'Reset password'),
      ('auth.reset_description', 'Enter your email address to receive a reset link.'),
      ('auth.send_link', 'Send link'),
      ('auth.back_to_login', 'Back to login'),
      ('auth.login_failed', 'Login failed'),
      ('auth.login_success', 'Logged in successfully'),
      ('auth.signup_failed', 'Registration failed'),
      ('auth.confirmation_sent', 'Confirmation email sent'),
      ('auth.confirmation_description', 'Please check your inbox and confirm your registration.'),
      ('auth.error', 'Error'),
      ('auth.email_sent', 'Email sent'),
      ('auth.email_sent_description', 'If an account exists with this email, you will receive a reset link.'),
      ('auth.new_password', 'Set new password'),
      ('auth.new_password_label', 'New password'),
      ('auth.change_password', 'Change password'),
      ('auth.password_changed', 'Password changed'),
      ('auth.invalid_link', 'Invalid or expired link.'),
      ('account.title', 'My Account'),
      ('account.admin', 'Admin'),
      ('account.profile', 'Profile'),
      ('account.addresses', 'Addresses'),
      ('account.payment', 'Payment'),
      ('account.orders', 'Orders'),
      ('account.tracking', 'Tracking'),
      ('account.personal_data', 'Personal Data'),
      ('account.personal_data_desc', 'Manage your personal information.'),
      ('account.phone', 'Phone'),
      ('account.save', 'Save'),
      ('account.save_error', 'Error saving'),
      ('account.save_success', 'Profile saved'),
      ('account.addresses_title', 'Shipping Addresses'),
      ('account.addresses_desc', 'Manage your shipping addresses via checkout.'),
      ('account.addresses_info', 'Your shipping addresses are saved automatically during checkout.'),
      ('account.addresses_edit', 'You can edit them during your next purchase at checkout.'),
      ('account.payment_title', 'Payment Methods'),
      ('account.payment_desc', 'Your payment methods are securely managed.'),
      ('account.payment_info', 'Payment methods are managed at checkout.'),
      ('account.payment_detail', 'Your payment data is securely stored for future orders.'),
      ('account.orders_title', 'Orders'),
      ('account.orders_desc', 'Overview of your previous orders.'),
      ('account.no_orders', 'No orders yet.'),
      ('account.no_orders_hint', 'Once you place an order, it will appear here.'),
      ('account.shop_now', 'Shop now'),
      ('account.tracking_title', 'Shipment Tracking'),
      ('account.tracking_desc', 'Track the status of your orders.'),
      ('account.no_tracking', 'No active shipments.'),
      ('account.no_tracking_hint', 'Tracking information will appear here once an order is shipped.'),
      ('brands.title', 'Our Brands'),
      ('brands.subtitle', 'Discover our carefully curated selection of premium equestrian brands – from saddles and bridles to riding apparel and accessories.'),
      ('brands.loading_error', 'Brands could not be loaded. Please try again later.'),
      ('brands.empty', 'No brands found.'),
      ('brands.empty_hint', 'There are currently no products in the shop.'),
      ('brands.not_found', 'Brand not found.'),
      ('brands.all_brands', 'All Brands'),
      ('brands.products_of', 'Products by {name}'),
      ('brands.no_products', 'Currently no products by {name} available.'),
      ('news.title', 'News & Updates'),
      ('news.subtitle', 'News about Horse & Rider, products and events.'),
      ('news.all_categories', 'All Categories'),
      ('news.all_months', 'All Months'),
      ('news.no_articles', 'No articles found.'),
      ('news.read_more', 'Read more'),
      ('news.page_of', 'Page {page} of {total}'),
      ('news.no_image', 'No image'),
      ('news.not_found', 'Article not found'),
      ('news.back_to_overview', 'Back to overview'),
      ('news.all_news', 'All News'),
      ('news.related_products', 'Related Products'),
      ('news.more_news', 'More News'),
      ('faq.title', 'Frequently Asked Questions'),
      ('faq.subtitle', 'Find answers to common questions about ordering, shipping and our services.'),
      ('faq.not_found_title', 'Didn''t find your question?'),
      ('faq.not_found_text', 'Contact us – we are happy to help!'),
      ('faq.contact_form', 'Contact Form'),
      ('kontakt.title', 'Contact'),
      ('kontakt.subtitle', 'We look forward to hearing from you! Visit us on site or send us a message.'),
      ('kontakt.thank_you', 'Thank you!'),
      ('kontakt.email_opened', 'Your email client has been opened. Please send the prepared message.'),
      ('kontakt.new_message', 'New Message'),
      ('kontakt.first_name', 'First name *'),
      ('kontakt.last_name', 'Last name *'),
      ('kontakt.email', 'Email *'),
      ('kontakt.phone', 'Phone'),
      ('kontakt.subject', 'Subject *'),
      ('kontakt.message', 'Message *'),
      ('kontakt.send', 'Send message'),
      ('kontakt.address', 'Address'),
      ('kontakt.opening_hours', 'Opening Hours'),
      ('general.loading', 'Loading…'),
      ('general.yes', 'Yes'),
      ('general.no', 'No')
    ) AS v(k, val)
  ) LOOP
    INSERT INTO ui_translations (key, locale, value, auto_generated)
    VALUES (t.k, 'en', t.val, false)
    ON CONFLICT (key, locale) DO UPDATE SET value = EXCLUDED.value, auto_generated = false, updated_at = now();
  END LOOP;
END $$